### ISSUE TITLE
Two html tags in the same line, returns to the first tag on the variable

### ISSUE THREAD

**Issue by github-rodrigobr92** [chuyik/brackets-snippets#15]
Hello. 
First of all, I would like to say that I loved your extension and it's helping me a lot.
But this one problem is annoying me like hell.
If I use two equal tags, like anchor tags, in the same line, the cursor gets moved to the first tag instead of the second. If you could check this out I would be really thankful. This will be my favorite brackets extension so far and I will remove Emmet. Thank you a lot for your work. :)

**Comment by chuyik** [comment]
Hi, thanks for the feedback!
Actually I realized this bug a while ago, but the reason I haven't fix it that's because it seems not so easy to be solved, and by the way I'm using another editor named `Atom` more often these days :joy:.

But as you point it out, I will spend some time on this at weekends, and hope that there's a better solution.

**Comment by chuyik** [comment]
Hi @github-rodrigobr92, I'm happy to say it's fixed in 1.7.0! Hope anything works fine.

**Comment by github-rodrigobr92** [comment]
Thank you man. You're the best. Sorry for not answering you before, didn't had a lot of time.
