### ISSUE TITLE
Send my custom snippets

### ISSUE THREAD

**Issue by erknrio** [chuyik/brackets-snippets#4]
Your extension is awesome and very easy to use. There is any way to send you my custom snippets?

**Comment by chuyik** [comment]
Yes please! You could send your snippets to my email address `crazyzyt#gmail.com` (# for @) to simply leave them here.

**Comment by chuyik** [comment]
I forgot to say... Now there's no way to export the snippets, so you could click `Debug` menu -> `Open Preferences File` to open `brackets.json`, and send the contents of `edc.brackets-snippets.hints` to me.

**Comment by erknrio** [comment]
Ok, but I have a problem with your plugin. Some times don't load. There is any shortcut to open the snippet manager?

**Comment by chuyik** [comment]
No shortcuts because I think there's already a bulb button on the edge right. Do you mean the button
![image](https://cloud.githubusercontent.com/assets/6262943/6148904/dee1a652-b23f-11e4-8acf-8c4797a528b1.png)
 didn't work? If so, I think there must be some errors I haven't encountered with.

If you like to share some error logs(which could help me fix this), you could click `Debug` -> `Show Developer Tools`, and the logs would be listed on `Console` tab :smiley:

**Comment by erknrio** [comment]
You have an email :).
