### ISSUE TITLE
File location for snippets

### ISSUE THREAD

**Issue by onetrev** [chuyik/brackets-snippets#8]
Just wondering if maybe at some point (if it's at all possible with how this extension is designed), snippets should be saved to somewhere other than the **brackets.json** file? I have some pretty large snippets and I'm thinking over time that file could get pretty large and it would be nice to have these saved separately.

Also when you remove the extension should your snippets be removed from brackets.json? I notice a lot of extensions leave behind their settings, probably not a big deal, just wondering what the Brackets best practice is?

**Comment by chuyik** [comment]
Hi onetrev, as you mentioned saving large pieces of data to `brackets.json` would make it a little bit dirty, and I also wonder if there are any other better solutions as I see many other extensions do the same way.
Maybe I should save the data to a independent file (yaml format for better human readable) instead, how about that?

**Comment by loucimj** [comment]
Hi, on the same direction about managing snippets, I'm trying to sync my two machines with the same snippets, and I was wondering if a solution using dropbox to sync the snippet files is viable.

**Comment by onetrev** [comment]
@chuyik ... Yes some sort of independent file would be great I think. Anything outside of brackets.json really is the key. Also this separate file may double as completing your To Do of export/import?

**Comment by chuyik** [comment]
Hi guys!
I choose to do the import/export rather than separate file, and please check out the new version!

Since Brackets would delete all files of the extension and override whenever extension updates, and I could not come up with a safe position to store the file elsewhere, so I think import/export might be better.

@loucimj If you want to sync the files between the machines, you could sync the `brackets.json` file. For more instructions please check out: [Migrating or Syncing Brackets Configuration
](https://github.com/adobe/brackets/wiki/Migrating-or-Syncing-Brackets-Configuration)
